# Site settings
title: GrowTye
email: GrowTye@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Your go-to place to grow with GrowTye. Visit for; tutorials,Infinite Activities, website recommendations and more! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "growtye.info" # the base hostname & protocol for your site

# User setting
owner: GrowTye
email: GrowTye@gmail.com
facebook_username: infiniteactivities
github_username: cvatch
address:
  - line: 
  - line: 
  - line: London, ON"
  # Feel free to add more lines here 
telephone: 
copyright: Infinite Activities

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker
